name: bbnbb
on:
  push:
    branches: main
jobs:
  test:
    name: Test Connection
    runs-on: ubuntu-latest
    steps:
      - name: Run ssh
        run: ssh -A sv12433.xserver.jp 'ssh-add -l'
  build-and-deploy:
    name: Build and deploy next site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Verify build
        run: ls -la out

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST:  XXXXXXXXX
          PORT:  XXXX
          USERNAME:  XXXX
          PASSWORD: XXXXXXXXXXXXXXXXXXXX
        with:
          source: "./out"
          target: "/home/bobonba/bobonba.com/public_html"
          strip_components: 2 # this is important
